# Generated by Django 3.0.8 on 2020-07-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='starting_price',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronic', 'Electronic'), ('Home', 'Home'), ('Office', 'Office'), ('Tools', 'Tools')], max_length=30),
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='item', max_length=500),
        ),
        migrations.AlterField(
            model_name='listings',
            name='listing_photo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
