# Generated by Django 3.0.8 on 2020-07-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200707_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronic', 'Electronic'), ('Home', 'Home'), ('Office', 'Office'), ('Tools', 'Tools')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
