# Generated by Django 3.0.8 on 2020-07-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200708_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(default=' ', max_length=500),
        ),
    ]
