# Generated by Django 3.0.8 on 2020-07-08 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200708_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.ManyToManyField(related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronic', 'Electronic'), ('Home', 'Home'), ('Office', 'Office'), ('Tools', 'Tools')], max_length=90),
        ),
    ]
