# Generated by Django 3.0.8 on 2020-07-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist_watchlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
